version: "3.8"
services:
  db:
    image: postgres:16.1-alpine
    container_name: "rehired-postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rehired
    ports:
      - "5430:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
